### ISSUE TITLE
Better safeguards against accidentable enabling of serial numbering on receipts

### ISSUE THREAD

**Issue by mlutfy** [jake-mw/CDNTaxReceipts#103] opened 2020-02-03 20:28 UTC
By default, cdntaxreceipts generates ID numbers based on the Contribution ID. This is the recommended mode. Some accountants do not like the gaps in receipt numbers (since not all contributions have charity receipts), so there is also an option for having a separate serial number.

PR #102 fixed a bug where this setting was being enabled by default. This can cause serious issues because it resets the serial numbering back to 1, therefore causing duplicate receipts numbers.

How can we make this more reliable? Some ideas:

- When serial_receipts are enabled, set the AUTO_INCREMENT to the max(contribution_id) + 1.
- Have more strong wording on the settings UI, so that admins know that they cannot go back once it has been changed.
- Freeze the setting once it has been set.
- Hide the setting from the admin interface? (document it in the README, how to enable via the Setting API)

cc @samuelsov

**Comment by KarinG** [comment] 2020-02-03 20:48
Thanks @mlutfy 

I've only ever had administrators from small/medium-size org ask me about serial numbering. All CPAs of large non-profits, including the BDO accountant we worked with writing this code much prefer the direct auditability of linking tax-receipt numbers to Contribution id. CRA has confirmed with them that what's really important here is that the numbers are **_unique_**. This method will remain the default/recommended method. 

Nevertheless we support Serial Receipt Numbers and going fwd I like your idea of hiding its setting/checkbox from the admin interface. This setting should only ever be set once. Switching back and forth should not be easy (via the GUI is too easy) as it will cause data issues. 

PS - It's not resetting it back to 1 -> it resets it back to id that the _log table was at. One org I audited this morning -> produces serial numbered receipts: 28406 - 33435 over the past couple months after upgrading to 1.5.0

**Comment by adixon** [comment] 2020-02-04 15:19
Yeah, I was thinking the same thing re: preventing changing the setting after it's been in use, either by hiding or freezing it. I think freezing would be better, with a note, to avoid confusion.

On the other hand, in the two cases that triggered the original requests, it was in response to audits, so preventing it from being changed kind of defeats the most common use case.

Another safeguard would be to add an extra prefix when using the serial numbering option, and I suppose that's what should be recommended if used (i.e. a change in prefix).

Perhaps we could put in a rule that if the box gets checked or unchecked, it forces the user to change the prefix - that would act as a safeguard and also a prevention of casual switching.

**Comment by KarinG** [comment] 2020-02-04 16:05
I must note that the serial number is still experimental and not always serial and that's another reason to put in safeguards. 

Below is a screenshot of happened to one of our clients who ran into the 'Serial Receipt Numbers checkbox became enabled by default' bug -> note that the receipt numbering is "Even Numbers Receipt Numbers" -> when using "Aggregate method". I have seen this in two clients I'm helping with their audit/fallout of this bug. 

So in addition to preventing accidental switching of Receipt Numbering schemes (either by bug or user), the Serial Receipts Numbers feature really needs more testing/bug fixes before it should even be an option.

![image](https://user-images.githubusercontent.com/5340555/73761407-09fe1100-472c-11ea-8591-e5501b3f5f7d.png)

**Comment by adixon** [comment] 2020-02-04 18:46
Yes, the "serial" numbering is more serial than the contribution number, but not completely serial. It doesn't fill in all the blanks for aggregate ones (though, that might be considered a feature?). At least, I could better document what it's doing.

**Comment by KarinG** [comment] 2020-02-04 20:02
Uh - that's not a feature. If serial numbering is not serial after all. That's an issue.

**Comment by jake-mw** [comment] 2020-02-04 20:32
Hi all,

I accepted & merged this feature so chiming in on this fallout :)

I'm with Karin on the following points:

1. Our ongoing commitment with tax receipting is that any feature exposed to end users needs to be solid. We have long held the position that too much is at stake for mistakes to happen; auditors tend not to overlook seemingly insignificant details. (I know this means we move too slowly at times with this extension, but it means our users have confidence in a critical function.)

2. "Counting by two" is not really a feature when the end user expects serial numbering. If their auditors are ok with gaps, they could continue using contribution numbering. If their auditors need to see no gaps - which is what serial numbering was introduced to resolve - then we need to deliver on that promise. The upshot of the current bug is that we have missed the core business rationale for adopting serial numbering.

With that preamble:

* I like @mlutfy's suggestion of a "freeze" on that checkbox when it is set (and agree with @adixon that a freeze is better than a hidden field). A forced prefix change is alright too, but may mean a well-meaning but unaware admin creates several different receipt stacks that their org now has to account for. I think it's most desirable to show the setting has been enabled, and prevent an admin from switching back and forth. "If you turn on Serial Numbering - proceed with caution, this is a permanent change."

* I've taken a quick look at trying to track down the "count by two" bug and I can't find it at quick glance. 

After brief discussion with Karin, we propose the following:

If anyone on this thread wishes to present a patch to deal with one or both issues noted above, we would gratefully review and accept it.

If no-one has time to adequately address these two issues, we are going to issue a release that removes the setting from the admin screen altogether (see: commitment #1 above). It will continue to function as a "back end" feature for orgs already on it, but we won't permit new users to turn it on until it is fully functional.

Thank you!

**Comment by adixon** [comment] 2020-02-04 21:05
I'm not opposed to your conclusion, just a note to say that my previous comment about how serial numbering works isn't right. I just looked at the code again, and looked at some entries in a client that's been using serial receipts for a few years now, and I don't think there are any obvious cases where you shouldn't have serial numbering. 

Specifically: the receipt_no should match the id of the cdntaxreceipts_log table. That id is an auto increment field. So the only way you would see gaps is if there were gaps in that table (i.e. if receipts were deleted, which they should never be ...).

Of course, that's the theory, and there is some table locking to prevent race conditions, but given Karin's experience, clearly some other issues are getting in here as well.

**Comment by KarinG** [comment] 2020-02-04 21:45
Yes that's theory -> Serial Numbering is not serial for the Aggregate pathway. 

**Two different clients that I audited:** 
- both used Serial Receipt Numbers [as a result of the bug] and 
- both are using Aggregate method as part of their process
- both getting "count by two" receipt numbers

**Comment by KarinG** [comment] 2020-02-11 13:31
More fallout: that -> re: number by two -> screenshot of which I posted above.

“... issued by email it looks like 41 of the donors received two receipts for the same donation, with each receipt the same except for the receipt number, which was one number different.”

I’m going to add a PR to remove the Serial numbering setting from the GUI.

**Comment by KarinG** [comment] 2020-02-11 15:29
Examining the _log table -> Tax Receipts for the same contribution were issued 92s apart. It is very likely that the client his a timeout (white-screen) and then restarted the job (by reloading the white-screen page e.g.). Somehow these jobs then collide and start to run in synchrony. With 'contribution id numbering' -> this is not an issue as the same receipt will be issued with the exact same number. With 'serial numbering' this is an issue. 

**Conclusion:** serial number requires a lock of some kind that prevents a second Tax Receipting process from starting when another one is in place.

![image](https://user-images.githubusercontent.com/5340555/74250569-0a585800-4ca8-11ea-8795-51557b79edb3.png)

**Comment by KarinG** [comment] 2020-07-29 17:37
Hello,

We have moved the project space for CDNTaxReceipts to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/cdntaxreceipts/

All issues have been migrated to: https://lab.civicrm.org/extensions/cdntaxreceipts/-/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
KarinG & DaveD

**Closed by KarinG** 2020-07-29 17:37 UTC
